# Generated by Django 2.0.3 on 2018-03-21 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Transaccion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=100)),
                ('habilitado', models.BooleanField(default=True)),
                ('decimales', models.IntegerField()),
                ('abreviatura', models.CharField(max_length=10)),
                ('simbolo', models.CharField(max_length=10)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Transaccion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
