# Generated by Django 2.0.3 on 2018-03-21 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0001_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('establecimiento', models.IntegerField()),
                ('punto_expedicion', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('CO', 'CONTADO'), ('CR', 'CRÉDITO')], default='CON', max_length=2)),
                ('timbrado', models.CharField(max_length=8)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Moneda')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Transaccion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=3, max_digits=21)),
                ('monto_eq', models.DecimalField(decimal_places=3, max_digits=21)),
                ('monto_iva', models.DecimalField(decimal_places=3, max_digits=21)),
                ('monto_iva_eq', models.DecimalField(decimal_places=3, max_digits=21)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.Factura')),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.IVA')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('tipo_doc', models.CharField(choices=[('RUC', 'REGISTRO ÚNICO DEL CONTRIBUYENTE'), ('CI', 'CÉDULA DE IDENTIDAD')], default='RUC', max_length=3)),
                ('nro_doc', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Transaccion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
